version: '3.2'

services:
  api:
    container_name: dentist-system-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
