version: '3.2'

services:
  api:
    container_name: dentist-system-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    env_file:
      - .env.development
    networks:
      - utils

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_DB: dentist-system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - utils

networks:
  utils:
    name: utils

volumes:
  postgres:
    driver: local
