name: Docker Image CI

on:
  push:
    branches: ['ci-test']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag hialves/dentist-system-api

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: dentist-system-api
          environment_name: Dentistsystemapi-env
          region: us-east-2
          existing_bucket_name: elasticbeanstalk-us-east-2-172646517932
          version_label: Sample Application
          deployment_package: deploy.zip
