name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag hialves/dentist-system-api

      - name: Upload the Docker image
        run: docker push hialves/dentist-system-api
